(cl:defpackage hoofdprogramma-msg
  (:use )
  (:export
   "<KWASTDETECTION>"
   "KWASTDETECTION"
   "<PICKANDPLACEACTION>"
   "PICKANDPLACEACTION"
   "<PICKANDPLACEACTIONFEEDBACK>"
   "PICKANDPLACEACTIONFEEDBACK"
   "<PICKANDPLACEACTIONGOAL>"
   "PICKANDPLACEACTIONGOAL"
   "<PICKANDPLACEACTIONRESULT>"
   "PICKANDPLACEACTIONRESULT"
   "<PICKANDPLACEFEEDBACK>"
   "PICKANDPLACEFEEDBACK"
   "<PICKANDPLACEGOAL>"
   "PICKANDPLACEGOAL"
   "<PICKANDPLACERESULT>"
   "PICKANDPLACERESULT"
  ))

