; Auto-generated. Do not edit!


(cl:in-package hoofdprogramma-msg)


;//! \htmlinclude PickAndPlaceGoal.msg.html

(cl:defclass <PickAndPlaceGoal> (roslisp-msg-protocol:ros-message)
  ((target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose))
   (kwast_type
    :reader kwast_type
    :initarg :kwast_type
    :type cl:string
    :initform ""))
)

(cl:defclass PickAndPlaceGoal (<PickAndPlaceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickAndPlaceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickAndPlaceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hoofdprogramma-msg:<PickAndPlaceGoal> is deprecated: use hoofdprogramma-msg:PickAndPlaceGoal instead.")))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <PickAndPlaceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hoofdprogramma-msg:target_pose-val is deprecated.  Use hoofdprogramma-msg:target_pose instead.")
  (target_pose m))

(cl:ensure-generic-function 'kwast_type-val :lambda-list '(m))
(cl:defmethod kwast_type-val ((m <PickAndPlaceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hoofdprogramma-msg:kwast_type-val is deprecated.  Use hoofdprogramma-msg:kwast_type instead.")
  (kwast_type m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickAndPlaceGoal>) ostream)
  "Serializes a message object of type '<PickAndPlaceGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'kwast_type))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'kwast_type))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickAndPlaceGoal>) istream)
  "Deserializes a message object of type '<PickAndPlaceGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'kwast_type) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'kwast_type) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickAndPlaceGoal>)))
  "Returns string type for a message object of type '<PickAndPlaceGoal>"
  "hoofdprogramma/PickAndPlaceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickAndPlaceGoal)))
  "Returns string type for a message object of type 'PickAndPlaceGoal"
  "hoofdprogramma/PickAndPlaceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickAndPlaceGoal>)))
  "Returns md5sum for a message object of type '<PickAndPlaceGoal>"
  "3bd52b27fc3662677b3ac39046a0c91e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickAndPlaceGoal)))
  "Returns md5sum for a message object of type 'PickAndPlaceGoal"
  "3bd52b27fc3662677b3ac39046a0c91e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickAndPlaceGoal>)))
  "Returns full string definition for message of type '<PickAndPlaceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/Pose target_pose~%string kwast_type~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickAndPlaceGoal)))
  "Returns full string definition for message of type 'PickAndPlaceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%geometry_msgs/Pose target_pose~%string kwast_type~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickAndPlaceGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
     4 (cl:length (cl:slot-value msg 'kwast_type))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickAndPlaceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PickAndPlaceGoal
    (cl:cons ':target_pose (target_pose msg))
    (cl:cons ':kwast_type (kwast_type msg))
))
