; Auto-generated. Do not edit!


(cl:in-package hoofdprogramma-msg)


;//! \htmlinclude PickAndPlaceResult.msg.html

(cl:defclass <PickAndPlaceResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PickAndPlaceResult (<PickAndPlaceResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickAndPlaceResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickAndPlaceResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hoofdprogramma-msg:<PickAndPlaceResult> is deprecated: use hoofdprogramma-msg:PickAndPlaceResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <PickAndPlaceResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hoofdprogramma-msg:success-val is deprecated.  Use hoofdprogramma-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickAndPlaceResult>) ostream)
  "Serializes a message object of type '<PickAndPlaceResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickAndPlaceResult>) istream)
  "Deserializes a message object of type '<PickAndPlaceResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickAndPlaceResult>)))
  "Returns string type for a message object of type '<PickAndPlaceResult>"
  "hoofdprogramma/PickAndPlaceResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickAndPlaceResult)))
  "Returns string type for a message object of type 'PickAndPlaceResult"
  "hoofdprogramma/PickAndPlaceResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickAndPlaceResult>)))
  "Returns md5sum for a message object of type '<PickAndPlaceResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickAndPlaceResult)))
  "Returns md5sum for a message object of type 'PickAndPlaceResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickAndPlaceResult>)))
  "Returns full string definition for message of type '<PickAndPlaceResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickAndPlaceResult)))
  "Returns full string definition for message of type 'PickAndPlaceResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickAndPlaceResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickAndPlaceResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PickAndPlaceResult
    (cl:cons ':success (success msg))
))
