// Generated by gencpp from file my_demo/BrushPoseFeedback.msg
// DO NOT EDIT!


#ifndef MY_DEMO_MESSAGE_BRUSHPOSEFEEDBACK_H
#define MY_DEMO_MESSAGE_BRUSHPOSEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_demo
{
template <class ContainerAllocator>
struct BrushPoseFeedback_
{
  typedef BrushPoseFeedback_<ContainerAllocator> Type;

  BrushPoseFeedback_()
    : status()  {
    }
  BrushPoseFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::my_demo::BrushPoseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_demo::BrushPoseFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct BrushPoseFeedback_

typedef ::my_demo::BrushPoseFeedback_<std::allocator<void> > BrushPoseFeedback;

typedef boost::shared_ptr< ::my_demo::BrushPoseFeedback > BrushPoseFeedbackPtr;
typedef boost::shared_ptr< ::my_demo::BrushPoseFeedback const> BrushPoseFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_demo::BrushPoseFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_demo::BrushPoseFeedback_<ContainerAllocator1> & lhs, const ::my_demo::BrushPoseFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_demo::BrushPoseFeedback_<ContainerAllocator1> & lhs, const ::my_demo::BrushPoseFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_demo::BrushPoseFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_demo::BrushPoseFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_demo::BrushPoseFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::my_demo::BrushPoseFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_demo/BrushPoseFeedback";
  }

  static const char* value(const ::my_demo::BrushPoseFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string status\n"
"\n"
;
  }

  static const char* value(const ::my_demo::BrushPoseFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrushPoseFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_demo::BrushPoseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_demo::BrushPoseFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DEMO_MESSAGE_BRUSHPOSEFEEDBACK_H
