(cl:defpackage my_demo-msg
  (:use )
  (:export
   "<BRUSHPOSEACTION>"
   "BRUSHPOSEACTION"
   "<BRUSHPOSEACTIONFEEDBACK>"
   "BRUSHPOSEACTIONFEEDBACK"
   "<BRUSHPOSEACTIONGOAL>"
   "BRUSHPOSEACTIONGOAL"
   "<BRUSHPOSEACTIONRESULT>"
   "BRUSHPOSEACTIONRESULT"
   "<BRUSHPOSEFEEDBACK>"
   "BRUSHPOSEFEEDBACK"
   "<BRUSHPOSEGOAL>"
   "BRUSHPOSEGOAL"
   "<BRUSHPOSERESULT>"
   "BRUSHPOSERESULT"
  ))

