; Auto-generated. Do not edit!


(cl:in-package my_demo-msg)


;//! \htmlinclude BrushPoseResult.msg.html

(cl:defclass <BrushPoseResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass BrushPoseResult (<BrushPoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BrushPoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BrushPoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_demo-msg:<BrushPoseResult> is deprecated: use my_demo-msg:BrushPoseResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <BrushPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_demo-msg:success-val is deprecated.  Use my_demo-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BrushPoseResult>) ostream)
  "Serializes a message object of type '<BrushPoseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BrushPoseResult>) istream)
  "Deserializes a message object of type '<BrushPoseResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BrushPoseResult>)))
  "Returns string type for a message object of type '<BrushPoseResult>"
  "my_demo/BrushPoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BrushPoseResult)))
  "Returns string type for a message object of type 'BrushPoseResult"
  "my_demo/BrushPoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BrushPoseResult>)))
  "Returns md5sum for a message object of type '<BrushPoseResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BrushPoseResult)))
  "Returns md5sum for a message object of type 'BrushPoseResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BrushPoseResult>)))
  "Returns full string definition for message of type '<BrushPoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BrushPoseResult)))
  "Returns full string definition for message of type 'BrushPoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BrushPoseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BrushPoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BrushPoseResult
    (cl:cons ':success (success msg))
))
