; Auto-generated. Do not edit!


(cl:in-package my_demo-msg)


;//! \htmlinclude BrushPoseGoal.msg.html

(cl:defclass <BrushPoseGoal> (roslisp-msg-protocol:ros-message)
  ((target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass BrushPoseGoal (<BrushPoseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BrushPoseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BrushPoseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_demo-msg:<BrushPoseGoal> is deprecated: use my_demo-msg:BrushPoseGoal instead.")))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <BrushPoseGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_demo-msg:target_pose-val is deprecated.  Use my_demo-msg:target_pose instead.")
  (target_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BrushPoseGoal>) ostream)
  "Serializes a message object of type '<BrushPoseGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BrushPoseGoal>) istream)
  "Deserializes a message object of type '<BrushPoseGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BrushPoseGoal>)))
  "Returns string type for a message object of type '<BrushPoseGoal>"
  "my_demo/BrushPoseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BrushPoseGoal)))
  "Returns string type for a message object of type 'BrushPoseGoal"
  "my_demo/BrushPoseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BrushPoseGoal>)))
  "Returns md5sum for a message object of type '<BrushPoseGoal>"
  "671ab81f81ce3fa4e8a3ac70c41ddb7c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BrushPoseGoal)))
  "Returns md5sum for a message object of type 'BrushPoseGoal"
  "671ab81f81ce3fa4e8a3ac70c41ddb7c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BrushPoseGoal>)))
  "Returns full string definition for message of type '<BrushPoseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose target_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BrushPoseGoal)))
  "Returns full string definition for message of type 'BrushPoseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose target_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BrushPoseGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BrushPoseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'BrushPoseGoal
    (cl:cons ':target_pose (target_pose msg))
))
