// Generated by gencpp from file hoofdprogramma/KwastDetection.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_KWASTDETECTION_H
#define HOOFDPROGRAMMA_MESSAGE_KWASTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace hoofdprogramma
{
template <class ContainerAllocator>
struct KwastDetection_
{
  typedef KwastDetection_<ContainerAllocator> Type;

  KwastDetection_()
    : pose()
    , kwast_type()  {
    }
  KwastDetection_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , kwast_type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _kwast_type_type;
  _kwast_type_type kwast_type;





  typedef boost::shared_ptr< ::hoofdprogramma::KwastDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::KwastDetection_<ContainerAllocator> const> ConstPtr;

}; // struct KwastDetection_

typedef ::hoofdprogramma::KwastDetection_<std::allocator<void> > KwastDetection;

typedef boost::shared_ptr< ::hoofdprogramma::KwastDetection > KwastDetectionPtr;
typedef boost::shared_ptr< ::hoofdprogramma::KwastDetection const> KwastDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::KwastDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::KwastDetection_<ContainerAllocator1> & lhs, const ::hoofdprogramma::KwastDetection_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.kwast_type == rhs.kwast_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::KwastDetection_<ContainerAllocator1> & lhs, const ::hoofdprogramma::KwastDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::KwastDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::KwastDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::KwastDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8790f86ce3eccb0d6b3eb32c5c4a515";
  }

  static const char* value(const ::hoofdprogramma::KwastDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8790f86ce3eccb0ULL;
  static const uint64_t static_value2 = 0xd6b3eb32c5c4a515ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/KwastDetection";
  }

  static const char* value(const ::hoofdprogramma::KwastDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"string kwast_type\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::hoofdprogramma::KwastDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.kwast_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KwastDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::KwastDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::KwastDetection_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "kwast_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.kwast_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_KWASTDETECTION_H
