// Generated by gencpp from file hoofdprogramma/PickAndPlaceResult.msg
// DO NOT EDIT!


#ifndef HOOFDPROGRAMMA_MESSAGE_PICKANDPLACERESULT_H
#define HOOFDPROGRAMMA_MESSAGE_PICKANDPLACERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hoofdprogramma
{
template <class ContainerAllocator>
struct PickAndPlaceResult_
{
  typedef PickAndPlaceResult_<ContainerAllocator> Type;

  PickAndPlaceResult_()
    : success(false)  {
    }
  PickAndPlaceResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> const> ConstPtr;

}; // struct PickAndPlaceResult_

typedef ::hoofdprogramma::PickAndPlaceResult_<std::allocator<void> > PickAndPlaceResult;

typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceResult > PickAndPlaceResultPtr;
typedef boost::shared_ptr< ::hoofdprogramma::PickAndPlaceResult const> PickAndPlaceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator1> & lhs, const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator1> & lhs, const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hoofdprogramma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hoofdprogramma/PickAndPlaceResult";
  }

  static const char* value(const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool success\n"
;
  }

  static const char* value(const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickAndPlaceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hoofdprogramma::PickAndPlaceResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOOFDPROGRAMMA_MESSAGE_PICKANDPLACERESULT_H
