<?xml version="1.0"?>
<package format="2">
  <name>hoofdprogramma</name>
  <version>0.0.1</version>
  <description>Hoofdprogramma voor kwasten sorteren</description>

  <maintainer email="student@todo.todo">student</maintainer>
  <license>MIT</license>

  <!-- Build tools -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Dependencies for messages/actions -->
  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>

  <!-- ROS dependencies -->
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>actionlib</depend>
  <depend>actionlib_msgs</depend>

  <export>
    <!-- No export needed -->
  </export>
</package>
